(function () {
  const root = document.querySelector('#newsletter'); const status = document.querySelector('#status');
  const esc = (value = '') => String(value).replace(/[&<>'"]/g, char => ({ '&':'&amp;', '<':'&lt;', '>':'&gt;', "'":'&#39;', '"':'&quot;' })[char]);
  const image = (source, alt, className = '') => source ? `<img class="${className}" src="${esc(source)}" alt="${esc(alt)}">` : '';
  const paragraph = value => esc(value).replace(/\n\n/g, '</p><p>');
  const render = d => `<div class="shell"><header class="hero"><div class="brand">${image(d.brand.logo,d.brand.logoAlt,'brand-logo')}<span>${esc(d.brand.name)}</span></div><p class="hero-edition">${esc(d.hero.eyebrow)}</p><div class="hero-copy"><h1>${esc(d.hero.title).replace(/\n/g,'<br>')}</h1><p class="hero-summary">${esc(d.hero.summary)}</p></div><aside class="core-lessons"><p>${esc(d.brand.coreLessonsTitle)}</p><ol>${d.brand.coreLessons.map(x=>`<li><span>${esc(x.order)}</span> <strong>${esc(x.text)}</strong></li>`).join('')}</ol></aside></header><div class="content"><section class="semester"><p class="eyebrow">${esc(d.semester.label)}</p><p>${esc(d.semester.body)}</p></section><section class="regional"><p class="eyebrow">${esc(d.regional.label)}</p><h2 class="section-heading">${esc(d.regional.title)}</h2>${d.regional.blocks.map(b=>`<div class="regional-block"><p>${esc(b.text)}</p>${image(b.image,b.alt,'regional-image')}</div>`).join('')}</section><section class="campus"><p class="eyebrow">${esc(d.campusExpansion.label)}</p><h2 class="section-heading">${esc(d.campusExpansion.title)}</h2><p>${paragraph(d.campusExpansion.body)}</p><figure>${image(d.campusExpansion.image,d.campusExpansion.alt,'campus-image')}<figcaption>${esc(d.campusExpansion.caption)}</figcaption></figure></section><section class="student-stories"><p class="eyebrow">STUDENT STORY</p><h2 class="section-heading">학생 간증</h2><div class="student-grid">${d.studentStories.map(s=>`<article class="student-card">${image(s.image,s.alt,'student-photo')}<div><h3>${esc(s.title)}</h3><blockquote>“${esc(s.quote)}”</blockquote><cite>— ${esc(s.name)} · ${esc(s.role)}</cite></div></article>`).join('')}</div></section><section class="prayer"><p class="eyebrow">PRAYER REQUESTS</p><h2 class="section-heading">함께 기도해 주세요</h2><ul class="prayer-list">${d.prayerRequests.map(x=>`<li>${esc(x)}</li>`).join('')}</ul></section><section class="support"><div><p class="eyebrow">PARTNERSHIP</p><h2>${esc(d.support.title)}</h2><p>${esc(d.support.body)}</p></div><dl class="details"><dt>${esc(d.support.accountLabel)}</dt><dd>${d.support.accounts.map(esc).join('<br><br>')}</dd></dl></section><nav class="archive"><h2 class="section-heading">지난 소식</h2><div class="archive-list">${d.archive.map(x=>`<a href="${esc(x.url)}">${esc(x.label)} →</a>`).join('')}</div></nav></div><footer><p>${esc(d.brand.koreanName)} · ${esc(d.footer.address)}</p><p>${esc(d.footer.copyright)}</p></footer></div>`;
  if (window.NEWSLETTER_CONTENT) { root.innerHTML = render(window.NEWSLETTER_CONTENT); status.textContent = '8월호 미리보기입니다.'; }
  document.querySelector('#content-file').addEventListener('change', event => { const file=event.target.files[0]; if(!file)return; const reader=new FileReader(); reader.onload=()=>{try{root.innerHTML=render(JSON.parse(reader.result));status.textContent='미리보기를 표시했습니다.'}catch{status.textContent='파일을 읽지 못했습니다. newsletter.json 파일을 다시 선택해 주세요.'}}; reader.readAsText(file,'utf-8'); });
})();
